const calendario = [
      {"fecha":"09/05/26",
        "hora": "11:30",
        "nombre":"Nado Día de las Madres",
        "lugar":"Playa La Colorada",
        "distancia":"consultar",
        "descripcion":"N/A",
        "organizacion": "NAF MVD",
        "inscripcion":""
    },
      {"fecha":"30/05/26",
        "nombre":"Rutas de Nado",
        "lugar":"Playa Ramírez",
        "distancia":"consultar",
        "descripcion":"N/A",
        "inscripcion":""
    },
      {"fecha":"06/06/26",
        "nombre":"Nado Cumpleañero",
        "lugar":"Playa Cerro",
        "distancia":"consultar",
        "descripcion":"N/A",
        "inscripcion":""
    },
      {"fecha":"07/06/26",
        "nombre":"5ta. Edición Travesía Piedra Alta",
        "lugar":"Prado Piedra Alta, Florida",
        "distancia":"500/1000/2000 metros",
        "descripcion":"Cazuela de lentejas y medalla finisher",
        "inscripcion":"https://shorturl.at/zLPsZ"},
      {"fecha":"20/06/26","nombre":"Rutas de Nado","lugar":"Playa Solymar","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"21/06/26","nombre":"Entrada del Invierno","lugar":"consultar","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"21/06/26","nombre":"Brazadas Solidarias (NAF Maldonado)","lugar":"Muelle Mailhos","distancia":"Se sugiere desde el muelle de Mailhos hasta el muelle de la Parada 3 y regreso.","descripcion":"Colaboración: $300 o $500 a beneficio de la Escuela España.","inscripcion":"@nafmaldonado en instagram"},
      {"fecha":"29/06/26","nombre":"Luna Llena","lugar":"consultar","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"11/07/26","nombre":"Concordia Nada en Invierno","lugar":"Concordia","distancia":"500m, 1k y 2k","descripcion":"Incluye remera oficial del evento, premiación por categorías, merienda de confraternidad (sábado), almuerzo (domingo), seguro del deportista, ingreso bonificado a Termas, cronometraje con chip electrónico.","inscripcion":"https://www.encarrera.com.ar/naf/?encarrera=inscripcion"},
      {"fecha":"11/07/26","nombre":"Rural Trail. 5ta Edición, Desafío Zagarzazú","lugar":"Balneario Zagarzazú. Carmelo, Colonia","distancia":"consultar","descripcion":"4k | 8k","inscripcion":""},
      {"fecha":"18/07/26","nombre":"Rutas de Nado","lugar":"Playa La Floresta / Costa Azul","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"15/08/26","nombre":"Nado Cumpleañero","lugar":"Playa Cerro","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"22/08/26","nombre":"Rutas de Nado","lugar":"Playa Piriápolis","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"24/08/26","nombre":"Nostalgia","lugar":"consultar","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"28/08/26","nombre":"Luna Llena","lugar":"consultar","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"19/09/26","nombre":"Rutas de Nado","lugar":"Muelle Mailhos (Maldonado)","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"22/09/26","nombre":"Entrada de la Primavera","lugar":"consultar","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"26/09/26","nombre":"Luna Llena","lugar":"consultar","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"26/10/26","nombre":"Luna Llena","lugar":"consultar","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"08/11/26","nombre":"Riachuelo","lugar":"Colonia","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"14/11/26","nombre":"Aquathlon NAF Montevideo","lugar":"Playa Cerro","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"24/11/26","nombre":"Luna Llena","lugar":"consultar","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"21/12/26","nombre":"Entrada del Verano","lugar":"consultar","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"23/12/26","nombre":"Luna Llena","lugar":"consultar","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"24/12/26","nombre":"Nado Navideño","lugar":"consultar","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"31/12/26","nombre":"Nado Fin de Año","lugar":"consultar","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"10/02/27","nombre":"Aniversario NAF Montevideo","lugar":"consultar","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"","nombre":"Hielo","lugar":"consultar","distancia":"consultar","descripcion":"N/A","inscripcion":""},
      {"fecha":"","nombre":"Despedida Fin de Año","lugar":"consultar","distancia":"consultar","descripcion":"Fecha a confirmar","inscripcion":""}
    ];
